name: example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  functional_error_handling_dart:
    git:
      url: https://github.com/ishibashi-futos/functional_error_handling_dart.git
      ref: v0.1.0 # latest package version.

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
