name: functional_error_handling_dart
description: I want to use Either, Option, Try in the Dart world.
publish_to: 'no'
version: 0.1.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: 1.19.3
