name: workflows

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master, feature/** ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart: [2.14.4, latest]

    container:
      image:  google/dart:${{ matrix.dart }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        dart pub get
        dart pub global activate coverage
        dart pub global activate check_coverage
        apt update -y
        apt install lcov zip -y
    - name: Tests
      run: dart test --coverage=.coverage
    - name: Check Covergage
      run: |
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        format_coverage -l -c -i .coverage --report-on=lib --packages=.packages | check_coverage 98 | true
        dart pub global run coverage:format_coverage --packages=.packages --report-on=lib --lcov -o .coverage/lcov.info -i .coverage
        genhtml -o ./report .coverage/lcov.info
        zip -r dist_${{ matrix.dart }}.zip ./report/*
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: dist_${{ matrix.dart }}.zip
        retention-days: 3
