name: workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart: [2.14.4, latest]

    container:
      image:  google/dart:${{ matrix.dart }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dart pub get
    - name: Tests
      run: dart test
