name: workflows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart: [2.14.4, latest]

    container:
      image:  google/dart:${{ matrix.dart }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        dart pub get
        pub global activate coverage
        dart pub global activate check_coverage
    - name: Tests
      run: dart test --coverage=.coverage
    - name: Check Covergage
      run: format_coverage -l -c -i .coverage --report-on=lib --packages=.packages | check_coverage 98
